# SPDX-FileCopyrightText: 2023 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rating-api
  namespace: default
  labels:
    app: user-rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: user-rating-api
          image: [ INSERT_AWS_ACCOUNT_ID ].dkr.ecr.eu-north-1.amazonaws.com/userrating:latest
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: '1.0.0'
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "200m"
              memory: "400Mi"