apiVersion: v1
kind: Service
metadata:
  name: user-rating-api-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 8080