apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: [ INSERT_AWS_ACCOUNT_ID ].dkr.ecr.eu-north-1.amazonaws.com/redis:latest
          command:
            - "redis-server"
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            - "--appendonly"
            - "yes"
            - "--maxmemory-policy"
            - "volatile-lru"
            - "--maxmemory"
            - "1gb"
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: main-secret
                  key: password